version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: staff_db
    environment:
      POSTGRES_DB: staff_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - staff_network
    restart: unless-stopped

  # Приложение Go (опционально, если хотите запускать в Docker)
  app:
    build: .
    container_name: staff_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: staff_db
    networks:
      - staff_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  staff_network:
    driver: bridge
